[package]
name = "dp-barcode-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = {version = "0.31.0", features = ["bundled"]}
eframe = "0.27.2"
egui_extras = { version = "0.27.2", features = ["image"]}
egui-file-dialog = "0.5.0"
rand = "0.8.5"
chrono = "0.4.38"